application: yetanotherwebapp
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.3"
- name: jinja2
  version: "2.6"
- name: yaml
  version: "3.10"
- name: pycrypto
  version: "2.3"